### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by leafac** [vitallan/skinator#5]
It would be nice to include a version number in skinator. The benefits are fairly obvious.

I recommend a way of showing the version number when calling the tool itself. `python skinator.py -v` is probably a good interface for that.

Also, consider tagging with git every new release. It keeps things easy to diff and regress.

**Comment by vitallan** [comment]
Really necessary. Once I work on this project again, i'll add the version number. I'll leave this issue open, so i can remember :)

**Comment by leafac** [comment]
@vitallan closing this as stale.
